<?php include 'views/templates/_partials/header.html'; ?>

<body>
    <?php include 'views/templates/_partials/sidebar.phtml'; ?>
    <h1 id="title" class="text-primary">Companies</h1>
    <div class="container">
        <div id="companies" class="mt-4">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Department</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($companies as $company): ?>
                        <tr>
                            <td><?php echo $company->getId(); ?></td>
                            <td><?php echo $company->getName(); ?></td>
                            <td><?php echo $company->getDepartment(); ?></td>
                            <td><a href="/admin/companies/company/<?php echo $company->getId(); ?>" class="btn btn-success">Preview</a></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>

    <?php include 'views/templates/_partials/scripts.html'; ?>
</body>

<?php include 'views/templates/_partials/footer.html'; ?>